# Generated by Django 2.1.5 on 2019-02-01 07:37

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
